apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "project.fullname" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
data:
  secret.yaml: {{ .Values.secret | toYaml | b64enc }}
